- hosts: all
  become: yes
  vars_files:
      - vars.yml
  roles:
      - geerlingguy.php
      - nginxinc.nginx
      - geerlingguy.mysql
      - geerlingguy.composer
  tasks:
      - name: Copy project
        synchronize:
            src: ../../
            dest: "{{ project_dir }}"

      - name: Deploy Nginx config
        template:
            src: nginx.conf.j2
            dest: /etc/nginx/conf.d/default.conf

      - name: Install MySQL timezones
        shell: mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p{{ mysql_passwd }} mysql

      - name: Deploy .env according to MySQL conf
        template:
            src: env.j2
            dest: "{{ project_dir }}/.env"

      - name: Composer install
        shell: cd {{ project_dir }} && php -d memory_limit=-1 $(which composer) install

      - name: Chmod var directory
        file:
            path: "{{ project_dir }}/var"
            owner: www-data
            mode: 0777
            recurse: yes

      - name: Import MySQL database if needed
        shell: mysql -u root -p{{ mysql_passwd }} {{ mysql_db }} < {{ project_dir }}/ansible/dump.sql
        when: import_sql_database is defined

      - name: Add Yarn repo
        shell: |
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

      - name: Install Yarn
        apt:
            name: yarn
            update_cache: yes

      - name: Install packages based on package.json
        yarn:
            path: "{{ project_dir }}"

      - name: Export FosJsRouting
        make:
            chdir: "{{ project_dir }}"
            target: export_routing

      - name: Compile the frontend
        make:
            chdir: "{{ project_dir }}"
            target: encore

      - name: Restart nginx
        service:
            name: nginx
            state: restarted

      - name: Restart PHP FPM
        service:
            name: php{{ php_default_version_debian}}-fpm
            state: restarted
